Added Style guide for Flutter repo
palash25/best-practices-checklist pull request #34
Opened 2021-05-07 06:39 UTC by fartem

2021-05-07 07:08 UTC, palash25 commented on README.md
> +- [Style guide for Flutter repo](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo)
i want the list to be about languages rather than frameworks, could you just add it to the dart section and remove the flutter section please.

2021-05-07 07:08 UTC, palash25 requested changes
minor nit

2021-05-07 07:15 UTC, fartem commented
@palash25 I'm fixed this issue.

2021-05-08 06:06 UTC, palash25 approved these changes

2021-05-08 06:06 UTC, merged

2021-05-08 06:07 UTC, palash25 commented
thank you ❤️